spring.application.name=CustomerService

# Activation
app.activation.button-url=${ACTIVATION_BUTTON_URL}
app.activation.success-url=${ACTIVATION_SUCCESS_URL}
app.activation.fail-url=${ACTIVATION_FAIL_URL}
app.activation.token-liveness-hours=24

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=900000

# Spring
spring.data.web.pageable.max-page-size=100

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Hikari CP
spring.datasource.hikari.maximum-pool-size=8

# Security
app.security.max-sessions=5
app.security.refresh-token-liveness-days=7
app.security.idempotency-key-hours=24

# Internal
app.internal.api-key=${INTERNAL_API_KEY}

# Agreements
app.agreements.mandatory=TERMS_OF_SERVICE,PRIVACY_POLICY,LOYALTY_PROGRAM_TERMS

# Messages
app.messages.registration-success=Registration is successful. Please check your inbox to activate your account.
app.messages.resend-activation=Activation link was sent again. Please check your inbox to activate your account.

# Cleanup
app.cleanup.refresh-token.batch=${REFRESH_TOKEN_CLEANUP_BATCH_SIZE}

# OpenAPI
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration